<?php
/**
 * @var \Payrexx\PaymentGateway\Block\Adminhtml\System\Config\ConnectPlatformButton $block
 */
?>

<button type="button" class="action-default" id="connect_platform_button">
    <span><?= $block->escapeHtml( __( 'Connect To Platform' ) ) ?></span>
</button>

<div id="payrexx_message_container" style="padding-top: 10px;"></div>

<script type="text/javascript">
    require([
        'jquery',
        'mage/translate'
    ], function ($, $t) {
        'use strict';

        // Wait for the document to be fully loaded
        $(function () {
            // Attach a click event handler to our custom button
            $('#connect_platform_button').on('click', function () {

                const platformElement = $('[name="groups[payrexx][groups][credentials][fields][platform][value]"]');
                const platformUrl = platformElement.val();
                if (!platformUrl) {
                    $('#payrexx_message_container')
                        .html('<div class="message message-warning">' + 'Please Select a Platform' + '</div>');
                    return;
                }
                let popupWindow = createPopup(platformUrl);

                let popupCheck;
                popupCheck = setInterval(() => {
                    if (popupWindow.closed) {
                        popupWindow = null;
                        clearInterval(popupCheck);
                    }
                })

            });
        });

        // Receive postMessage from popup
        window.addEventListener('message', function (event) {
            const messageContainer = $('#payrexx_message_container');
            if (!event.data || !event.data.instance) {
                messageContainer.html('<div class="message message-error">' + 'Credentials could not be imported' + '</div>');
                return;
            }

            const apiKey = event.data.instance.apikey;
            const instance = event.data.instance.name;

            const apiKeyElement = $('input[name="groups[payrexx][groups][credentials][fields][api_secret][value]"]');
            apiKeyElement.val(apiKey)

            const instanceNameElement = $('input[name="groups[payrexx][groups][credentials][fields][instance_name][value]"]');
            instanceNameElement.val(instance);

            messageContainer.html('<div class="message message-success">' + 'Credentials imported successfully' + '</div>');

            $('#save').click();
        });

        const createPopup = (platformUrl) => {
            const popupWidth = 900;
            const popupHeight = 900;

            // Get the parent window's size and position
            const dualScreenLeft = window.screenLeft !== undefined ? window.screenLeft : window.screenX;
            const dualScreenTop = window.screenTop !== undefined ? window.screenTop : window.screenY;

            const width = window.innerWidth
                ? window.innerWidth
                : document.documentElement.clientWidth
                    ? document.documentElement.clientWidth
                    : screen.width;

            const height = window.innerHeight
                ? window.innerHeight
                : document.documentElement.clientHeight
                    ? document.documentElement.clientHeight
                    : screen.height;

            const left = dualScreenLeft + (width - popupWidth) / 2;
            const top = dualScreenTop + (height - popupHeight) / 2;

            const params = `width=${popupWidth},height=${popupHeight},top=${top},left=${left},resizable=no,scrollbars=yes`
            const url = `https://login.${platformUrl}?action=connect&plugin_id=4`;
            return window.open(url, 'Connect Payrexx', params);
        }
    });
</script>
